### ISSUE TITLE
Add contributors stats

### ISSUE THREAD

**Issue by shakeelmohamed** [redaxmedia/githubstats#4]
I'd love to see a chart of repo contributors over time! Not sure how feasible that is, at a minimum the total count would be really nice.

According to the [docs](https://developer.github.com/v3/repos/statistics/) it looks like the endpoint is `/repos/:owner/:repo/stats/contributors` - which you'd just need to get the length of to know the number of contributors. 

I'm open to helping out, but I haven't taken a look at the code yet. Posting to see your thoughts, thanks! :smile:

**Comment by redaxmedia** [comment]
Thank you for the request, I will check it out...

**Comment by shakeelmohamed** [comment]
Are you open to a pull request? I think the graph would be meaningful over the long-term, it wouldn't look great if repo suddenly gained or lost a a large amount of contributors

**Comment by redaxmedia** [comment]
Of course, I'm open to pull requests. Drop me a line if you need existence on parts of the code: info@redaxmedia.com
