### ISSUE TITLE
Builds graph appears to break the design

### ISSUE THREAD

**Issue by shakeelmohamed** [redaxmedia/githubstats#5]
Check out the screenshots, I don't remember seeing this before but maybe I overlooked it.
The builds chart gets wrapped into a new (third) column that's not visible until scrolling over and to the top.

Repro URL: http://githubstats.com/zen-audio-player/zen-audio-player.github.io

![capturfiles_10](https://cloud.githubusercontent.com/assets/1480063/15036665/4270a804-1247-11e6-8919-f5d164366069.png)
![capturfiles_9](https://cloud.githubusercontent.com/assets/1480063/15036667/453d20b2-1247-11e6-9fb3-fb4778cbe2a1.png)

**Comment by redaxmedia** [comment]
Thank you for submitting. I had similar issues a couple of months ago.

Please tell me your operation system, browser and version.

**Comment by shakeelmohamed** [comment]
I'm on OS X 10.11.4, Chrome 50. It looks fine in Safari though

**Comment by redaxmedia** [comment]
Sorry, but I'm on Ubuntu and Windows only and therefore can't fix it.

**Comment by redaxmedia** [comment]
I replace multi column with classic floats - this fixed the issue
