### ISSUE TITLE
Add download stats

### ISSUE THREAD

**Issue by Bluscream** [redaxmedia/githubstats#9]
Add download statistics.

**Comment by redaxmedia** [comment]
Will do on the next refactoring...

**Comment by Bluscream** [comment]
Nice, thank you :)

**Comment by redaxmedia** [comment]
The Download API is deprecated: https://developer.github.com/v3/repos/downloads/

GitHub Stats also needs a date format in the response to calculate the graphs. It does no work with downloads anyway. Sorry

**Comment by Bluscream** [comment]
Use the not deprecated https://developer.github.com/v3/repos/releases/ API then to list the downloads...

**Comment by redaxmedia** [comment]
All right, I did not see that.

**Comment by Bluscream** [comment]
Thanks <3
